### ISSUE TITLE
example 

### ISSUE THREAD

**Issue by marabooy** [taftse/camelot-auth#1]
could you provide a little example on how to use it .. maybe on the wiki or something 
would provide a great head start

**Comment by taftse** [comment]
i hope to get some time later today or early tomorrow to update the read-me with an example and get the registration aspect working

**Comment by marabooy** [comment]
thanks ..will appreciate that

**Comment by taftse** [comment]
I have added some documentation to the Repo and added the files to the wiki please let me know if you find any bugs
