### ISSUE TITLE
Can't pull from Composer

### ISSUE THREAD

**Issue by splitinfinities** [taftse/camelot-auth#27]
I'm having an issue installing this from composer (with laravel):
"t4s/camelot-auth": "*" (Can't find the package)
returns: 
  Problem 1
    - The requested package t4s/camelot-auth could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

---

Alternatively, 
"taftse/camelot-auth": " \* " (Laravel framework isn't good to work with)
returns... this: 
    - Conclusion: remove laravel/framework v4.1.12
    - Conclusion: don't install laravel/framework v4.1.12
    - Conclusion: don't install laravel/framework v4.1.11
    - Conclusion: don't install laravel/framework v4.1.10
    - Conclusion: don't install laravel/framework v4.1.9
    - Conclusion: don't install laravel/framework v4.1.8
    - Conclusion: don't install laravel/framework v4.1.7
    - Conclusion: don't install laravel/framework v4.1.6
    - Conclusion: don't install laravel/framework v4.1.5
    - Conclusion: don't install laravel/framework v4.1.4
    - Conclusion: don't install laravel/framework v4.1.3
    - Installation request for t4s/camelot-auth dev-master -> satisfiable by t4s/camelot-auth[dev-master].
    - Conclusion: don't install laravel/framework v4.1.2
    - Conclusion: don't install laravel/framework v4.1.1
    - t4s/camelot-auth dev-master requires illuminate/support 4.0.x -> satisfiable by laravel/framework[v4.0.0, v4.0.1, v4.0.10, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9], illuminate/support[v4.0.0, v4.0.1, v4.0.10, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9].
    - don't install illuminate/support v4.0.0|don't install laravel/framework v4.1.0
    - don't install illuminate/support v4.0.1|don't install laravel/framework v4.1.0
    - don't install illuminate/support v4.0.10|don't install laravel/framework v4.1.0
    - don't install illuminate/support v4.0.2|don't install laravel/framework v4.1.0
    - don't install illuminate/support v4.0.3|don't install laravel/framework v4.1.0
    - don't install illuminate/support v4.0.4|don't install laravel/framework v4.1.0
    - don't install illuminate/support v4.0.5|don't install laravel/framework v4.1.0
    - don't install illuminate/support v4.0.6|don't install laravel/framework v4.1.0
    - don't install illuminate/support v4.0.7|don't install laravel/framework v4.1.0
    - don't install illuminate/support v4.0.8|don't install laravel/framework v4.1.0
    - don't install illuminate/support v4.0.9|don't install laravel/framework v4.1.0
    - Can only install one of: laravel/framework[v4.1.0, v4.0.0].
    - Can only install one of: laravel/framework[v4.1.0, v4.0.1].
    - Can only install one of: laravel/framework[v4.1.0, v4.0.10].
    - Can only install one of: laravel/framework[v4.1.0, v4.0.2].
    - Can only install one of: laravel/framework[v4.1.0, v4.0.3].
    - Can only install one of: laravel/framework[v4.1.0, v4.0.4].
    - Can only install one of: laravel/framework[v4.1.0, v4.0.5].
    - Can only install one of: laravel/framework[v4.1.0, v4.0.6].
    - Can only install one of: laravel/framework[v4.1.0, v4.0.7].
    - Can only install one of: laravel/framework[v4.1.0, v4.0.8].
    - Can only install one of: laravel/framework[v4.1.0, v4.0.9].
    - Installation request for laravel/framework 4.1.\* -> satisfiable by laravel/framework[v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9].

**Comment by ipavelic** [comment]
Hi!

I got the same problem and solution was in changing minimum stability in composer.json to "dev".

Hope it will help someone!

**Comment by splitinfinities** [comment]
Totally going to try this, thank you!

**Comment by abishekrsrikaanth** [comment]
Is there a way to use this plugin with the latest Laravel dev 4.2?

**Comment by taftse** [comment]
i have updated the installation instructions which should fix the problem
