### ISSUE TITLE
 php artisan publish:config ts4/config results in InvalidArgumentException

### ISSUE THREAD

**Issue by fabianmu** [taftse/camelot-auth#8]
step5 of the laravel 4 `php artisan publish:config ts4/config` installation throws:

```
[InvalidArgumentException]
There are no commands defined in the "publish" namespace.
```

**Comment by JulienTant** [comment]
Hi,

The good command is actually config:publish

Hope this help.

**Comment by fabianmu** [comment]
nope,
`php artisan config:publish ts4/config` results in `Configuration not found.` and 
`php artisan config:publish t4s/config` returns the same error.

**Comment by fabianmu** [comment]
`php artisan config:publish t4s/camelot-auth` works
